default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 784512
  host: localhost
  port: 5432

development:
  <<: *default
  database: my_site_development

test:
  <<: *default
  database: my_site_test

production:
  primary: &primary_production
    <<: *default
    database: my_site_production
    username: my_site
    password: <%= ENV["MY_SITE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: my_site_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_site_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_site_production_cable
    migrations_paths: db/cable_migrate
